### ISSUE TITLE
Hey what do you know, there is /OFFICIAL/ API documentation...

### ISSUE THREAD

**Issue by Rhinorulz** [Hitakashi/Hitbox-API#10]
just no place on the site links to it... http://developers.hitbox.tv
I've been using your resources here, and in trying to found them again found another project that actually linked to the api documentation.
but the official documentation only covers /Media, /User, /Followers, /Games, /Team, /Auth/token, and /Injests
so your documentation is still better.
Just thought I'd share with you, and hopefully I can get Navi working soon.

**Comment by AquatikJustice** [comment]
The "Official" API you linked is also GROSSLY outdated, which is why Hitakashi started documenting the API here in the first place. For example, it lists the base URL for the API as "http://api.hitbox.tv". The ACTUAL base URL is "http://www.hitbox.tv/api"

It's a real shame that Hitbox doesn't seem to take their API seriously because a major reason (IMO) that Twitch was able to grow is due to developers being able to effectively use their API to create apps, web services, etc that facilitated innovation and allowed streamers to think outside the box. For many streamers who would like to either start streaming or who want to make the switch to Hitbox, they find that the apps available to help them are few and far in-between and that discourages a lot of would-be converts.

**Comment by Hitakashi** [comment]
I'm one of the people that's updating the official developer documentation. I essentially have everything done excluding a few APIs that I excluded due to almost no need for developers to use them. (EX: Create Account, You can't actually do it without fiddling a lot). 

I've already sent the updates to a staff member for updating developer.hitbox.tv, It's only a matter of time.

@AquatikJustice From what I heard, Both are essentially the same URL, It's just that /api/ is cached differently than api.hitbox.tv. (But yes, Sadly it seems /api/ works a lot more often than api.)

They've also started added OAuth/3rd Party Apps (Check your account settings),  Hopefully they flesh this out and allow users to create applications with scopes. It's awful that there's only one type of token - everything.

Edit: As a note, I will keep both documentations up-to-date as much as possible. I will be putting more 'bleeding-edge' APIs (AKA, Just added) to this doc. 

I'll be updating the official documentation as long as staff wants to continue it. :)

**Comment by Hitakashi** [comment]
http://developers.hitbox.tv/ has been updated with my written documentation. I do think I wrote the doc for them quite a bit better than this (Github) one, but I've documented more APIs here. (Youtube, Facebook, and Twitter Posts. etc)
